import Foundation
import Testing
@testable import RPlusCore

// Generated by scratchpad bh-probe/probe.mjs from Node (labs-bh*.mjs). Synthetic data only. Do not edit by hand.
@Suite("Labs BH extra") struct LabsBHExtraTests {
    static let parseCases: [(String, String, [String: [Double]]?, [String: Double]?, BHResult)] = [
        ("cbc", "HEMATOLOGIA\nBIOMETRIA HEMATICA COMPLETA\nEstudio Resultado Unidades Valor de Referencia\nRBC B 3.52 M/uL 4.04 - 6.13\nHGB B 10.4 g/dL 12.20 - 18.10\nHCT B 31.6 % 37.7 - 53.7\nMCV * 89 fL 80 - 97\nMCH * 29.5 pg 27.0 - 31.2\nMCHC * 32.9 g/dL 29.9 - 34.2\nRDW A 15.9 % 11.6 - 14.8\nWBC A 14.20 K/uL 4.00 - 11.00\nNEU A 11.90 K/uL 2.00 - 6.90\nNEU% A 83.8 % 37.0 - 80.0\nLYM * 1.10 K/uL 0.60 - 3.40\nLYM% B 7.7 % 10.0 - 50.0\nMONO * 0.700 K/uL 0.000 - 0.900\nMONO% * 4.93 % 0.00 - 12.00\nEOS * 0.300 K/uL 0.000 - 0.700\nEOS% * 2.11 % 0.00 - 7.00\nBASO * 0.050 K/uL 0.000 - 0.200\nBASO% * 0.35 % 0.00 - 2.50\nPLT * 210.00 K/uL 142.00 - 424.00\nMPV * 8.1 fL 7.4 - 10.4", nil, nil, BHResult(visible: "BH\tHb 10.4*  Hto 31.6*  VCM 89  HCM 29.5  Leu 14.2*  Neu 11.9*  Eos 0.3  Plt 210", coagVisible: "", extras: ["Baso": "0.050", "BasoPct": "0.35", "CHCM": "32.9", "EosPct": "2.11", "Lin": "1.10", "LinPct": "7.7", "MPV": "8.1", "Mono": "0.700", "MonoPct": "4.93", "NeuPct": "83.8", "RBC": "3.52*", "RDW": "15.9*"])),
        ("cbc+ret", "HEMATOLOGIA\nBIOMETRIA HEMATICA COMPLETA\nEstudio Resultado Unidades Valor de Referencia\nRBC B 3.52 M/uL 4.04 - 6.13\nHGB B 10.4 g/dL 12.20 - 18.10\nHCT B 31.6 % 37.7 - 53.7\nMCV * 89 fL 80 - 97\nMCH * 29.5 pg 27.0 - 31.2\nMCHC * 32.9 g/dL 29.9 - 34.2\nRDW A 15.9 % 11.6 - 14.8\nWBC A 14.20 K/uL 4.00 - 11.00\nNEU A 11.90 K/uL 2.00 - 6.90\nNEU% A 83.8 % 37.0 - 80.0\nLYM * 1.10 K/uL 0.60 - 3.40\nLYM% B 7.7 % 10.0 - 50.0\nMONO * 0.700 K/uL 0.000 - 0.900\nMONO% * 4.93 % 0.00 - 12.00\nEOS * 0.300 K/uL 0.000 - 0.700\nEOS% * 2.11 % 0.00 - 7.00\nBASO * 0.050 K/uL 0.000 - 0.200\nBASO% * 0.35 % 0.00 - 2.50\nPLT * 210.00 K/uL 142.00 - 424.00\nMPV * 8.1 fL 7.4 - 10.4\nRETICULOCITOS * 1.0 % 0.5 - 1.5", nil, nil, BHResult(visible: "BH\tHb 10.4*  Hto 31.6*  VCM 89  HCM 29.5  Ret 1  RetC 0.7 (arregenerativa)  Leu 14.2*  Neu 11.9*  Eos 0.3  Plt 210", coagVisible: "", extras: ["Baso": "0.050", "BasoPct": "0.35", "CHCM": "32.9", "EosPct": "2.11", "Lin": "1.10", "LinPct": "7.7", "MPV": "8.1", "Mono": "0.700", "MonoPct": "4.93", "NeuPct": "83.8", "RBC": "3.52*", "RDW": "15.9*", "Ret": "1"])),
        ("soloRet prior Hto", "HEMATOLOGIA\nRETICULOCITOS * 4.0 % 0.5 - 2.5", nil, ["Hto": 30], BHResult(visible: "BH\tRet 4*  RetC 2.67 (regenerativa)", coagVisible: "", extras: ["Ret": "4*"])),
        ("soloHto prior Ret", "HEMATOLOGIA\nHCT B 28.0 % 37 - 53", nil, ["Ret": 3.5], BHResult(visible: "BH\tHto 28*  RetC 2.18 (regenerativa)", coagVisible: "", extras: [:])),
        ("wbc only prior both", "HEMATOLOGIA\nWBC B 6.0 10^3/uL 4 - 11", nil, ["Hto": 30, "Ret": 4], BHResult(visible: "BH\tLeu 6", coagVisible: "", extras: [:])),
        ("hemolizada", "HEMATOLOGIA\nBIOMETRIA HEMATICA COMPLETA\nEstudio\t\tResultado\tUnidades\tValor de Referencia\nRBC\t\n*\nM/uL\t3.94 - 5.32\nHGB\t\n*\ng/dL\t12.00 - 15.70\nHCT\t\n*\n%\t35.5 - 47.3\nPLT\t\n*\nK/uL\t142.00 - 424.00", nil, nil, BHResult(visible: "", coagVisible: "", extras: [:])),
        ("hemolizada dif", "HEMATOLOGIA\nEstudio\t\tResultado\tUnidades\tValor de Referencia\nNEU%\t\n*\n%\t38.6 - 75.2\nLYM%\t\n*\n%\t15.0 - 48.5", nil, nil, BHResult(visible: "", coagVisible: "", extras: [:])),
        ("ret + gases hct", "HEMATOLOGIA\nRETICULOCITOS\nRETICULOCITOS\t*\t2.8\t%\t0.5 - 1.5\nGASOMETRIA ARTERIAL\nHCT\t*\t37\t%\t37 - 53", nil, nil, BHResult(visible: "BH\tHto 37  Ret 2.8*  RetC 2.3 (regenerativa)", coagVisible: "", extras: ["Ret": "2.8*"])),
        ("ret only", "HEMATOLOGIA\nRETICULOCITOS * 1.0 % 0.5 - 1.5", nil, nil, BHResult(visible: "BH\tRet 1", coagVisible: "", extras: ["Ret": "1"])),
        ("dif manual + ret + frotis", "HEMATOLOGIA\nDIFERENCIAL MANUAL\nSEGMENTADOS\n*\n95\n%\nBANDAS\n*\n2\n%\t0 - 5\nRETICULOCITOS\nEstudio\t\tResultado\tUnidades\tValor de Referencia\nRETICULOCITOS\n*\n1.0\n%\t0.5 - 1.5\nFROTIS DE SANGRE PERIFERICA\nHIPOCROMIA +", nil, nil, BHResult(visible: "BH\tRet 1", coagVisible: "", extras: ["Bandas": "2", "NeuPct": "95", "Ret": "1"])),
        ("cbc + frotis", "HEMATOLOGIA\nBIOMETRIA HEMATICA COMPLETA\nEstudio Resultado Unidades Valor de Referencia\nRBC B 3.52 M/uL 4.04 - 6.13\nHGB B 10.4 g/dL 12.20 - 18.10\nHCT B 31.6 % 37.7 - 53.7\nMCV * 89 fL 80 - 97\nMCH * 29.5 pg 27.0 - 31.2\nMCHC * 32.9 g/dL 29.9 - 34.2\nRDW A 15.9 % 11.6 - 14.8\nWBC A 14.20 K/uL 4.00 - 11.00\nNEU A 11.90 K/uL 2.00 - 6.90\nNEU% A 83.8 % 37.0 - 80.0\nLYM * 1.10 K/uL 0.60 - 3.40\nLYM% B 7.7 % 10.0 - 50.0\nMONO * 0.700 K/uL 0.000 - 0.900\nMONO% * 4.93 % 0.00 - 12.00\nEOS * 0.300 K/uL 0.000 - 0.700\nEOS% * 2.11 % 0.00 - 7.00\nBASO * 0.050 K/uL 0.000 - 0.200\nBASO% * 0.35 % 0.00 - 2.50\nPLT * 210.00 K/uL 142.00 - 424.00\nMPV * 8.1 fL 7.4 - 10.4\n\nFROTIS DE SANGRE PERIFERICA\nBANDAS 4 %\nMIELOCITOS 1 %\nMETAMIELOCITOS 0 %\nPROMIELOCITOS 0 %\nBLASTOS 0 %", nil, nil, BHResult(visible: "BH\tHb 10.4*  Hto 31.6*  VCM 89  HCM 29.5  Leu 14.2*  Neu 11.9*  Eos 0.3  Plt 210", coagVisible: "", extras: ["Bandas": "4", "Baso": "0.050", "BasoPct": "0.35", "Blastos": "0", "CHCM": "32.9", "EosPct": "2.11", "Lin": "1.10", "LinPct": "7.7", "MPV": "8.1", "Metamielo": "0", "Mielo": "1", "Mono": "0.700", "MonoPct": "4.93", "NeuPct": "83.8", "Promielo": "0", "RBC": "3.52*", "RDW": "15.9*"])),
        ("no bh", "NO HAY BH AQUI", nil, nil, BHResult(visible: "", coagVisible: "", extras: [:])),
        ("empty", "", nil, nil, BHResult(visible: "", coagVisible: "", extras: [:])),
        ("diff manual only", "HEMATOLOGIA\nDIFERENCIAL MANUAL\nEstudio\t\tResultado\tUnidades\tValor de Referencia\nSEGMENTADOS\t\nA\n78\n%\t50 - 70\nBANDAS\t\n*\n2\n%\t0 - 5\nLINFOCITOS\t\n*\n15\n%\t10 - 50\nMONOCITOS\t\n*\n4\n%\t0 - 12\nEOSINOFILOS\t\n*\n1\n%\t0 - 7\nBASOFILOS\t\n*\n0\n%\t0 - 2\n", nil, nil, BHResult(visible: "BH:\n  Dif.\tSeg 78%*  Lin 15%  Mono 4%  Eos 1%  Band 2%", coagVisible: "", extras: ["Bandas": "2", "BasoPct": "0", "EosPct": "1", "LinPct": "15", "MonoPct": "4", "NeuPct": "78"])),
        ("coag only", "COAGULACION\nTIEMPO DE PROTROMBINA A 15.8 seg 11.0 - 14.0\nINR A 1.42 0.80 - 1.20\nTIEMPO DE TROMBOPLASTINA PARCIAL * 31.0 seg 25.0 - 35.0\nFIBRINOGENO A 520 mg/dL 200 - 400", nil, nil, BHResult(visible: "", coagVisible: "COAG\tTP 15.8*  TTP 31  INR 1.42*  Fib 520*", extras: [:])),
        ("cbc + coag", "HEMATOLOGIA\nBIOMETRIA HEMATICA COMPLETA\nEstudio Resultado Unidades Valor de Referencia\nRBC B 3.52 M/uL 4.04 - 6.13\nHGB B 10.4 g/dL 12.20 - 18.10\nHCT B 31.6 % 37.7 - 53.7\nMCV * 89 fL 80 - 97\nMCH * 29.5 pg 27.0 - 31.2\nMCHC * 32.9 g/dL 29.9 - 34.2\nRDW A 15.9 % 11.6 - 14.8\nWBC A 14.20 K/uL 4.00 - 11.00\nNEU A 11.90 K/uL 2.00 - 6.90\nNEU% A 83.8 % 37.0 - 80.0\nLYM * 1.10 K/uL 0.60 - 3.40\nLYM% B 7.7 % 10.0 - 50.0\nMONO * 0.700 K/uL 0.000 - 0.900\nMONO% * 4.93 % 0.00 - 12.00\nEOS * 0.300 K/uL 0.000 - 0.700\nEOS% * 2.11 % 0.00 - 7.00\nBASO * 0.050 K/uL 0.000 - 0.200\nBASO% * 0.35 % 0.00 - 2.50\nPLT * 210.00 K/uL 142.00 - 424.00\nMPV * 8.1 fL 7.4 - 10.4\nCOAGULACION\nTIEMPO DE PROTROMBINA A 15.8 seg 11.0 - 14.0\nINR A 1.42 0.80 - 1.20\nTIEMPO DE TROMBOPLASTINA PARCIAL * 31.0 seg 25.0 - 35.0\nFIBRINOGENO A 520 mg/dL 200 - 400", nil, nil, BHResult(visible: "BH\tHb 10.4*  Hto 31.6*  VCM 89  HCM 29.5  Leu 14.2*  Neu 11.9*  Eos 0.3  Plt 210", coagVisible: "COAG\tTP 15.8*  TTP 31  INR 1.42*  Fib 520*", extras: ["Baso": "0.050", "BasoPct": "0.35", "CHCM": "32.9", "EosPct": "2.11", "Lin": "1.10", "LinPct": "7.7", "MPV": "8.1", "Mono": "0.700", "MonoPct": "4.93", "NeuPct": "83.8", "RBC": "3.52*", "RDW": "15.9*"])),
        ("dd campo", "HEMATOLOGIA\nDIMERO D\nDIMERO D\tA\n881\nng/mL\t0.0 - 500.0\nUEF (UNIDADES EQUIVALENTES DE FIBRINOGENO\t*\nCOMENTARIO\t*", nil, nil, BHResult(visible: "", coagVisible: "COAG\tDD 881*", extras: [:])),
        ("d-dimero lt", "COAGULACION\nD-DIMERO * <0.19 ug/mL 0.00 - 0.50", nil, nil, BHResult(visible: "", coagVisible: "COAG\tDD <0.19", extras: [:])),
        ("priorRefs no ranges", "HGB 9.1 g/dL\nHCT 27 %\nWBC 12.5 K/uL\nPLT 90 K/uL", ["Hb": [12, 16], "Hto": [36, 46], "Leu": [4, 11], "Plt": [150, 450]], nil, BHResult(visible: "BH\tHb 9.1*  Hto 27*  Leu 12.5*  Plt 90*", coagVisible: "", extras: [:])),
        ("comma decimals", "HGB 9,5 g/dL 12,0 - 16,0\nHCT 30,2 % 36 - 46\nWBC 7,3 K/uL 4 - 11", nil, nil, BHResult(visible: "BH\tHb 9.5*  Hto 30.2*  Leu 7.3", coagVisible: "", extras: [:])),
        ("index only", "RBC B 3.2 M/uL 4.0 - 6.0\nMCHC * 33 g/dL 30 - 35\nRDW A 17 % 11 - 15\nMPV * 9 fL 7 - 10", nil, nil, BHResult(visible: "BH\tEri 3.2*  CHCM 33  RDW 17*  VPM 9", coagVisible: "", extras: [:])),
        ("index + diff", "RBC B 3.2 M/uL 4.0 - 6.0\nRDW A 17 % 11 - 15\nHEMATOLOGIA\nDIFERENCIAL MANUAL\nEstudio\t\tResultado\tUnidades\tValor de Referencia\nSEGMENTADOS\t\nA\n78\n%\t50 - 70\nBANDAS\t\n*\n2\n%\t0 - 5\nLINFOCITOS\t\n*\n15\n%\t10 - 50\nMONOCITOS\t\n*\n4\n%\t0 - 12\nEOSINOFILOS\t\n*\n1\n%\t0 - 7\nBASOFILOS\t\n*\n0\n%\t0 - 2\n", nil, nil, BHResult(visible: "BH:\n  Hem.\tEri 3.2*  RDW 17*\n  Dif.\tSeg 78%*  Lin 15%  Mono 4%  Eos 1%  Band 2%", coagVisible: "", extras: ["Bandas": "2", "BasoPct": "0", "EosPct": "1", "LinPct": "15", "MonoPct": "4", "NeuPct": "78"])),
        ("ret + diff", "RETICULOCITOS * 2.0 % 0.5 - 1.5\nHEMATOLOGIA\nDIFERENCIAL MANUAL\nEstudio\t\tResultado\tUnidades\tValor de Referencia\nSEGMENTADOS\t\nA\n78\n%\t50 - 70\nBANDAS\t\n*\n2\n%\t0 - 5\nLINFOCITOS\t\n*\n15\n%\t10 - 50\nMONOCITOS\t\n*\n4\n%\t0 - 12\nEOSINOFILOS\t\n*\n1\n%\t0 - 7\nBASOFILOS\t\n*\n0\n%\t0 - 2\n", nil, nil, BHResult(visible: "BH\tRet 2*", coagVisible: "", extras: ["Bandas": "2", "BasoPct": "0", "EosPct": "1", "LinPct": "15", "MonoPct": "4", "NeuPct": "78", "Ret": "2*"])),
        ("ret + diff prior hto", "RETICULOCITOS * 2.0 % 0.5 - 1.5\nHEMATOLOGIA\nDIFERENCIAL MANUAL\nEstudio\t\tResultado\tUnidades\tValor de Referencia\nSEGMENTADOS\t\nA\n78\n%\t50 - 70\nBANDAS\t\n*\n2\n%\t0 - 5\nLINFOCITOS\t\n*\n15\n%\t10 - 50\nMONOCITOS\t\n*\n4\n%\t0 - 12\nEOSINOFILOS\t\n*\n1\n%\t0 - 7\nBASOFILOS\t\n*\n0\n%\t0 - 2\n", nil, ["Hto": 40.5], BHResult(visible: "BH\tRet 2*  RetC 1.8 (arregenerativa)", coagVisible: "", extras: ["Bandas": "2", "BasoPct": "0", "EosPct": "1", "LinPct": "15", "MonoPct": "4", "NeuPct": "78", "Ret": "2*"])),
        ("tab layout values", "HEMATOLOGIA\nEstudio\t\tResultado\tUnidades\tValor de Referencia\nHGB\t\nB\n8.7\ng/dL\t12.00 - 15.70\nHCT\t\nB\n26.1\n%\t35.5 - 47.3\nWBC\t\n*\n5.4\nK/uL\t4.00 - 11.00\nPLT\t\nB\n88\nK/uL\t142.00 - 424.00", nil, nil, BHResult(visible: "BH\tHb 8.7*  Hto 26.1*  Leu 5.4  Plt 88*", coagVisible: "", extras: [:])),
        ("lowercase", "hgb 11.2 g/dl 12 - 16\nhct 34 % 36 - 46\nplt 300 k/ul 150 - 450", nil, nil, BHResult(visible: "BH\tHb 11.2*  Hto 34*  Plt 300", coagVisible: "", extras: [:])),
        ("atipicos", "SEGMENTADOS 60 % 50 - 70\nLINF. ATIPICOS 5 %\nBLASTOS 2 %\nPROMIELOCITOS 1 %", nil, nil, BHResult(visible: "BH:\n  Dif.\tSeg 60%  Prom 1%  Blast 2%*  Atip 5%", coagVisible: "", extras: ["Atipicos": "5", "Blastos": "2", "NeuPct": "60", "Promielo": "1"])),
        ("variantes", "LINFOCITOS 30 % 20 - 40\nVARIANTES 3 %\nMIELOCITOS 2 %", nil, nil, BHResult(visible: "BH:\n  Dif.\tLin 30%  Mielo 2%*  Atip 3%", coagVisible: "", extras: ["Atipicos": "3", "LinPct": "30", "Mielo": "2"])),
        ("diff zeros", "SEGMENTADOS 0 % 50 - 70\nBANDAS 0 %\nLINFOCITOS 40 % 20 - 40", nil, nil, BHResult(visible: "BH:\n  Dif.\tLin 40%", coagVisible: "", extras: ["Bandas": "0", "LinPct": "40", "NeuPct": "0"])),
        ("diff prior refs", "SEGMENTADOS 82 %\nLINFOCITOS 9 %", ["LinPct": [20, 40], "NeuPct": [50, 70]], nil, BHResult(visible: "BH:\n  Dif.\tSeg 82%*  Lin 9%*", coagVisible: "", extras: ["LinPct": "9", "NeuPct": "82"])),
        ("inr only", "INR 3.4 0.8 - 1.2", nil, nil, BHResult(visible: "", coagVisible: "COAG\tINR 3.4*", extras: [:])),
        ("inr huge", "INR 12.5 0.8 - 1.2", nil, nil, BHResult(visible: "", coagVisible: "COAG\tINR 12.5*", extras: [:])),
        ("fibrinogeno accent", "FIBRINÓGENO * 310 mg/dL 200 - 400", nil, nil, BHResult(visible: "", coagVisible: "COAG\tFib 310", extras: [:])),
        ("hemoglobina words", "HEMOGLOBINA 13.4 g/dL 12 - 16\nHEMATOCRITO 40 % 36 - 46\nERITROCITOS 4.5 M/uL 4 - 5.5", nil, nil, BHResult(visible: "BH\tHb 13.4  Hto 40", coagVisible: "", extras: ["RBC": "4.5"])),
        ("wbc no lym", "WBC 9 K/uL 4 - 11\nMONO 0.5 K/uL 0 - 0.9\nBASO 0.02 K/uL 0 - 0.2", nil, nil, BHResult(visible: "BH\tLeu 9", coagVisible: "", extras: ["Baso": "0.02", "Mono": "0.5"])),
        ("lym no wbc", "LYM 1.5 K/uL 0.6 - 3.4\nMONO 0.5 K/uL 0 - 0.9", nil, nil, BHResult(visible: "", coagVisible: "", extras: [:])),
        ("ret regen boundary", "RETICULOCITOS * 2 % 0.5 - 1.5\nHCT 45 % 36 - 46", nil, nil, BHResult(visible: "BH\tHto 45  Ret 2*  RetC 2 (regenerativa)", coagVisible: "", extras: ["Ret": "2*"])),
        ("neu pct cases", "NEUTROFILOS% 66 % 40 - 75\nEOSINOFILOS% 3 %\nBASOFILOS% 1 %\nMONOCITOS% 8 %", nil, nil, BHResult(visible: "BH:\n  Dif.\tSeg 66%  Mono 8%  Eos 3%  Baso 1%", coagVisible: "", extras: ["BasoPct": "1", "EosPct": "3", "MonoPct": "8", "NeuPct": "66"])),
    ]
    @Test(arguments: parseCases.indices) func parseBH(_ i: Int) {
        let c = Self.parseCases[i]
        #expect(LabBH.parseBH(c.1, priorRefs: c.2, priorBhValues: c.3) == c.4, "\(c.0)")
    }
    static let mergeBhCases: [([String?], String, String)] = [
        (["BH\tHb 8.84*  Hto 25.5*  VCM 93  HCM 32.4  Leu 2.89*  Neu 2.65  Eos 0.02  Plt 12.5*", "BH\tRet 1"], "BH\tHb 8.84*  Hto 25.5*  VCM 93  HCM 32.4  Ret 1  RetC 0.57 (arregenerativa)  Leu 2.89*  Neu 2.65  Plt 12.5*", ""),
        (["BH\tRet 2.8  RetC 0.72 (arregenerativa)"], "BH\tRet 2.8  RetC 0.72 (arregenerativa)", ""),
        (["BH\tHb 10\nCOAG\tTP 12  INR 1.1", "BH\tHto 30  Ret 2", "BH\tPlt 140*\nCOAG\tTP 13.5*  Fib 450*"], "BH\tHb 10  Hto 30  Ret 2  RetC 1.33 (arregenerativa)  Plt 140*", "COAG\tTP 13.5*  INR 1.1  Fib 450*"),
        (["COAG\tTP 12", "HB nada"], "", ""),
        ([], "", ""),
        (["BH:\n  Hem.\tEri 3.1\n  Dif.\tSeg 70%", "BH:\n  Dif.\tSeg 71%*  Lin 20%  Mono 5%"], "BH:\n  Dif.\tSeg 71%*  Lin 20%  Mono 5%", ""),
        (["BH:\n  Hem.\tRet 1.5", "BH\tHto 33"], "BH\tHto 33  Ret 1.5  RetC 1.1 (arregenerativa)", ""),
        (["BH\tHb 9%*  Leu 4,5", nil, "BH\tHb 12"], "BH\tHb 9*  Leu 4.5", ""),
        (["BH:\n  Hem.\tEri 3.1\n  Coag.\tTP 12", "bh\tDif. Seg"], "BH:\n  Hem.\tEri 3.1", ""),
        (["  BH\tHb 7.1*  Plt 50*"], "BH\tHb 7.1*  Plt 50*", ""),
        (["BH\tHto 40  Ret 3", "BH\tRet 1  RetC 0.5 (arregenerativa)"], "BH\tHto 40  Ret 3  RetC 2.67 (regenerativa)", ""),
    ]
    @Test(arguments: mergeBhCases.indices) func mergeBh(_ i: Int) {
        let c = Self.mergeBhCases[i]
        let r = LabBH.mergeBhResLabRows(c.0)
        #expect(r.bh == c.1 && r.coag == c.2, "\(i): \(r)")
    }
    static let mergeCoagCases: [([String], String)] = [
        (["COAG\tTP 12  INR 1.1", "COAG\tTP 12.5*  TTP 30  Fib 400"], "COAG\tTP 12.5*  TTP 30  INR 1.1  Fib 400"),
        (["COAG\tZeta 1  Alfa 2  DD 0.5", "Coag.\tBeta 3  TP 11"], "COAG\tTP 11  DD 0.5  Alfa 2  Beta 3  Zeta 1"),
        (["BH\tHb 1", ""], ""),
        (["coag\tINR 2.5*  INR 1.0"], "COAG\tINR 2.5*"),
        (["COAG\tDD 0.3   TP 14 (11 - 14)  TP 14"], "COAG\tTP 14 (11 - 14)  DD 0.3"),
    ]
    @Test(arguments: mergeCoagCases.indices) func mergeCoag(_ i: Int) {
        let c = Self.mergeCoagCases[i]
        #expect(LabBH.mergeCoagResLabRows(c.0) == c.1)
    }
    static let flattenCases: [(String, String)] = [
        ("BH:\n  Hem.\tRet 1", "BH\tRet 1"),
        ("BH:\n  Hem.\tEri 3.11  Ret 1", "BH\tEri 3.11  Ret 1"),
        ("BH:\n  Hem.\tRet 1\n  Dif.\tSeg 71%*", "BH:\n  Hem.\tRet 1\n  Dif.\tSeg 71%*"),
        ("BH\tHb 8.84", "BH\tHb 8.84"),
        ("BH:\n  Hem.\tRet 1\n  Hem.\tRet 2", "BH:\n  Hem.\tRet 1\n  Hem.\tRet 2"),
        ("BH:\n\n  Hem.\tVPM 9  \n", "BH\tVPM 9"),
        ("BH:", "BH:"),
        ("", ""),
        ("BH:\n  Otra\tx", "BH:\n  Otra\tx"),
    ]
    @Test(arguments: flattenCases.indices) func flatten(_ i: Int) {
        let c = Self.flattenCases[i]
        #expect(LabBH.flattenBhHemOnlyVisible(c.0) == c.1)
    }
    static let trendCases: [(String, [String: String])] = [
        ("BH\tHb 8.84*  Hto 25.5*  VCM 93  Ret 1  RetC 0.57 (arregenerativa)  Leu 2,89*", ["Hb": "8.84|ab", "Hto": "25.5|ab", "Leu": "2.89|ab", "Ret": "1", "RetC": "0.57", "VCM": "93"]),
        ("BH:\n  Hem.\tEri 3.11  VPM 8.1\n  Dif.\tSeg 71%*  Band 3%  Atip 1%", ["Atipicos": "1", "Bandas": "3", "MPV": "8.1", "NeuPct": "71|ab", "RBC": "3.11"]),
        ("COAG\tTP 12.5*  TTP 30  INR >8  DD <0.19*", ["DD": "<0.19|ab", "INR": ">8", "TP": "12.5|ab", "TTP": "30"]),
        ("BH: Hb 9\nsin tab", [:]),
        ("- 5  Hb - Plt x Leu 7", [:]),
    ]
    @Test(arguments: trendCases.indices) func trendValues(_ i: Int) {
        let c = Self.trendCases[i]
        #expect(LabBH.parseBhTrendValuesFromResLab(c.0).mapValues { $0.val + ($0.ab ? "|ab" : "") } == c.1)
    }
    static let retiCases: [(String, String, String)] = [
        ("1", "29.1", "0.65 (arregenerativa)"),
        ("4", "30", "2.67 (regenerativa)"),
        ("2,5", "45", "2.5 (regenerativa)"),
        ("---", "40", "---"),
        ("0", "40", "0 (arregenerativa)"),
        ("1.5*", "30", "1 (arregenerativa)"),
        ("2", "45", "2 (regenerativa)"),
        ("abc", "40", "---"),
        ("3.333", "27", "2 (arregenerativa)"),
        ("", "40", "---"),
    ]
    @Test(arguments: retiCases.indices) func retiCorregido(_ i: Int) {
        let c = Self.retiCases[i]
        #expect(LabBH.computeRetiCorregido(c.0, c.1) == c.2)
    }
    static let extrasDisplayCases: [([String: String], String, String)] = [
        (["Baso": "0.050", "BasoPct": "0.35", "CHCM": "32.9", "EosPct": "2.11", "Lin": "1.10", "LinPct": "7.7", "MPV": "8.1", "Mono": "0.700", "MonoPct": "4.93", "NeuPct": "83.8", "RBC": "3.52*", "RDW": "15.9*"], "HEMATOLOGIA\nBIOMETRIA HEMATICA COMPLETA\nEstudio Resultado Unidades Valor de Referencia\nRBC B 3.52 M/uL 4.04 - 6.13\nHGB B 10.4 g/dL 12.20 - 18.10\nHCT B 31.6 % 37.7 - 53.7\nMCV * 89 fL 80 - 97\nMCH * 29.5 pg 27.0 - 31.2\nMCHC * 32.9 g/dL 29.9 - 34.2\nRDW A 15.9 % 11.6 - 14.8\nWBC A 14.20 K/uL 4.00 - 11.00\nNEU A 11.90 K/uL 2.00 - 6.90\nNEU% A 83.8 % 37.0 - 80.0\nLYM * 1.10 K/uL 0.60 - 3.40\nLYM% B 7.7 % 10.0 - 50.0\nMONO * 0.700 K/uL 0.000 - 0.900\nMONO% * 4.93 % 0.00 - 12.00\nEOS * 0.300 K/uL 0.000 - 0.700\nEOS% * 2.11 % 0.00 - 7.00\nBASO * 0.050 K/uL 0.000 - 0.200\nBASO% * 0.35 % 0.00 - 2.50\nPLT * 210.00 K/uL 142.00 - 424.00\nMPV * 8.1 fL 7.4 - 10.4", "BH ext\tEri 3.52*  CHCM 32.9  RDW 15.9*  VPM 8.1  Lin# 1.10  Mono# 0.700  Baso# 0.050  Seg 83.8%*  Lin 7.7%*  Mono 4.93%  Eos 2.11%  Baso 0.35%"),
        (["Bandas": "2", "BasoPct": "0", "EosPct": "1", "LinPct": "15", "MonoPct": "4", "NeuPct": "78"], "HEMATOLOGIA\nDIFERENCIAL MANUAL\nEstudio\t\tResultado\tUnidades\tValor de Referencia\nSEGMENTADOS\t\nA\n78\n%\t50 - 70\nBANDAS\t\n*\n2\n%\t0 - 5\nLINFOCITOS\t\n*\n15\n%\t10 - 50\nMONOCITOS\t\n*\n4\n%\t0 - 12\nEOSINOFILOS\t\n*\n1\n%\t0 - 7\nBASOFILOS\t\n*\n0\n%\t0 - 2\n", "BH ext\tSeg 78%*  Lin 15%  Mono 4%  Eos 1%  Baso 0%  Band 2%"),
        (["Bandas": "3", "Lin": "1.1", "NeuPct": "80", "RBC": "3.5*"], "", "BH ext\tEri 3.5*  Lin# 1.1  Seg 80%  Band 3%"),
        ([:], "", ""),
    ]
    @Test(arguments: extrasDisplayCases.indices) func extrasDisplayLine(_ i: Int) {
        let c = Self.extrasDisplayCases[i]
        #expect(LabBH.formatBhExtrasDisplayLine(c.0, c.1) == c.2)
    }
}
