import Foundation
import Testing
@testable import RPlusCore

/// Synthetic pastes from labs-some-table.test.mjs (plus a few edge cases).
/// Expected JSON = Node parseSomeReportTables output (probe: scratchpad some-probe/probe.test.mjs). Do not edit by hand.
private let someExtraCases: [(input: String, expected: String)] = [
    ("\nExpediente:\t9000012-1\tSolicitud:\t9000000020\nNombre:\tFICTICIO SINTETICO EJEMPLO CASOAI\tFecha Registro:\t10/06/2025 03:41:29 p. m.\nSexo:\tMASCULINO\tUbicación:\tEMERGENCIAS SHOCK TRAUMA CONSULTA\nEdad:\t43\tMedico:\tFICTICIO SINTETICO EJEMPLO A\n\nBACTERIOLOGIA\nEstudio\t\tResultado\tUnidades\tValor de Referencia\nFIBRAS VEGETALES\nFIBRAS VEGETALES\t\n*\nNEGATIVO\nTIPO DE MUESTRA\t\n*\nCITOQUIMICO DE LIQUIDOS CORPORALES\nRECUENTO\t\nA\n112\nLEUCOCITOS/MM3\t0.00 - 5.00\nASPECTO\t\n*\nXANTOCROMICO\nPOLIMORFONUCLEARES\t\n*\n60\n%\t\nLINFOCITOS\t\n*\n40\n%\t\nERITROCITOS\t\n*\nESCASOS\n/mm3\t\nGRAM\t\n*\nNEGATIVO\nCOMENTARIO\t\n*\nPERITONEAL\n\nQUIMICA CLINICA\nEstudio\t\tResultado\tUnidades\tValor de Referencia\nCITOQUIMICO DE LIQUIDOS CORPORALES\nEXAMEN QUIMICO\t\n*\n:\nDENSIDAD\t\n*\n1.010\nPH\t\n*\n7.5\nGLUCOSA\t\n*\n78.0\nmg/dL\t\nPROTEINAS\t\n*\n5100\nmg/dL\t\nLDH\t\n*\n77\nIU/L\t\nCITOQUIMICO DE\t\n*\nLIQUIDO DE ASCITIS\nALBUMINA\nALBUMINA\t\nB\n2.8\ng/dL\t3.2 - 5.5\nCOLESTEROL\nCOLESTEROL\t\nB\n56\nmg/dL\t130 - 200\nTRIGLICERIDOS\nTRIGLICERIDOS\t\n*\n40\nmg/dL\t35 - 150\n",
     ###"{"departments":[{"key":"BACTERIOLOGIA","label":"BACTERIOLOGIA","groups":[{"title":"FIBRAS VEGETALES","rows":[{"estudio":"FIBRAS VEGETALES","flag":"*","resultado":"NEGATIVO","unidades":"","ref":"","abnormal":false}],"tableVariant":"standard","fluidSource":"","_someNormalized":true},{"title":"CITOQUIMICO DE LIQUIDOS CORPORALES","rows":[{"estudio":"RECUENTO","flag":"A","resultado":"112","unidades":"LEUCOCITOS/MM3","ref":"0.00 - 5.00","abnormal":true},{"estudio":"ASPECTO","flag":"*","resultado":"XANTOCROMICO","unidades":"","ref":"","abnormal":false},{"estudio":"POLIMORFONUCLEARES","flag":"*","resultado":"60","unidades":"%","ref":"","abnormal":false},{"estudio":"LINFOCITOS","flag":"*","resultado":"40","unidades":"%","ref":"","abnormal":false},{"estudio":"ERITROCITOS","flag":"*","resultado":"ESCASOS","unidades":"/mm3","ref":"","abnormal":false},{"estudio":"GRAM","flag":"*","resultado":"NEGATIVO","unidades":"","ref":"","abnormal":false}],"tableVariant":"cito","fluidSource":"PERITONEAL","_someNormalized":true}]},{"key":"QUIMICA CLINICA","label":"QUIMICA CLINICA","groups":[{"title":"","rows":[{"estudio":"ALBUMINA","flag":"B","resultado":"2.8","unidades":"g/dL","ref":"3.2 - 5.5","abnormal":true},{"estudio":"COLESTEROL","flag":"B","resultado":"56","unidades":"mg/dL","ref":"130 - 200","abnormal":true},{"estudio":"TRIGLICERIDOS","flag":"*","resultado":"40","unidades":"mg/dL","ref":"35 - 150","abnormal":false}],"tableVariant":"standard"},{"title":"CITOQUIMICO DE LIQUIDOS CORPORALES","rows":[{"estudio":"DENSIDAD","flag":"*","resultado":"1.010","unidades":"","ref":"","abnormal":false},{"estudio":"PH","flag":"*","resultado":"7.5","unidades":"","ref":"","abnormal":false},{"estudio":"GLUCOSA","flag":"*","resultado":"78.0","unidades":"mg/dL","ref":"","abnormal":false},{"estudio":"PROTEINAS","flag":"*","resultado":"5100","unidades":"mg/dL","ref":"","abnormal":false},{"estudio":"LDH","flag":"*","resultado":"77","unidades":"IU/L","ref":"","abnormal":false}],"tableVariant":"cito","fluidSource":"ALBUMINA","_someNormalized":true}]}]}"###),
    ("\nHEMATOLOGIA\nBIOMETRIA HEMATICA COMPLETA\nEstudio\t\tResultado\tUnidades\tValor de Referencia\nHGB\t\n*\n12.40\ng/dL\t12.20 - 18.10\nHCT\t\n*\n39.8\n%\t37.7 - 53.7\nWBC\t\nA\n19.60\nK/uL\t4.00 - 11.00\nMCH\t\nB\n25.9\npg\t27.0 - 31.2\nRDW\t\nA\n16.9\n%\t11.6 - 14.8\n",
     ###"{"departments":[{"key":"HEMATOLOGIA","label":"HEMATOLOGIA","groups":[{"title":"BIOMETRIA HEMATICA COMPLETA","rows":[{"estudio":"HGB","flag":"*","resultado":"12.40","unidades":"g/dL","ref":"12.20 - 18.10","abnormal":false},{"estudio":"HCT","flag":"*","resultado":"39.8","unidades":"%","ref":"37.7 - 53.7","abnormal":false},{"estudio":"WBC","flag":"A","resultado":"19.60","unidades":"K/uL","ref":"4.00 - 11.00","abnormal":true},{"estudio":"MCH","flag":"B","resultado":"25.9","unidades":"pg","ref":"27.0 - 31.2","abnormal":true},{"estudio":"RDW","flag":"A","resultado":"16.9","unidades":"%","ref":"11.6 - 14.8","abnormal":true}],"tableVariant":"standard","fluidSource":"","_someNormalized":true}]}]}"###),
    ("Expediente:\t9000096-4\tSolicitud:\t2605291063\nBACTERIOLOGIA\nEstudio\t\tResultado\tUnidades\tValor de Referencia\nASPIRADO TRAQUEAL\nPRODUCTO\t\n*\nTINCION DE GRAM\t\n*\nESTADO DE CULTIVO\t\n*\nREPORTE PRELIMINAR\n*\nMICROORGANISMO\t\n*\nAcinetobacter baumannii\nCOMENTARIO:\t\n*\nCUENTA\t\n*\n3,200 UFC/mL\n*\nMICROORGANISMO\t\n*\nProteus mirabilis\nCOMENTARIO:\t\n*\nCUENTA\t\n*\n50,000 UFC/mL\n*",
     ###"{"departments":[{"key":"BACTERIOLOGIA","label":"BACTERIOLOGIA","groups":[{"title":"ASPIRADO TRAQUEAL","rows":[{"estudio":"MICROORGANISMO","flag":"*","resultado":"Acinetobacter baumannii","unidades":"","ref":"","abnormal":false},{"estudio":"CUENTA","flag":"*","resultado":"3,200 UFC/mL","unidades":"","ref":"","abnormal":false},{"estudio":"MICROORGANISMO","flag":"*","resultado":"Proteus mirabilis","unidades":"","ref":"","abnormal":false},{"estudio":"CUENTA","flag":"*","resultado":"50,000 UFC/mL","unidades":"","ref":"","abnormal":false}],"tableVariant":"standard","fluidSource":"","_someNormalized":true}]}]}"###),
    ("\nQUIMICA CLINICA\nEstudio\t\tResultado\tUnidades\tValor de Referencia\nALBUMINA\nALBUMINA\t\n*\n4.5\ng/dL\t3.2 - 5.5\nBILIRRUBINA\nBILIRRUBINA TOTAL\t\nA\n1.6\nmg/dL\t0.2 - 1.0\nBILIRRUBINA DIRECTA\t\nA\n0.7\nmg/dL\t0.0 - 0.2\nSODIO\nSODIO\t\nB\n124.3\nmmol/L\t135.0 - 145.0\n",
     ###"{"departments":[{"key":"QUIMICA CLINICA","label":"QUIMICA CLINICA","groups":[{"title":"","rows":[{"estudio":"ALBUMINA","flag":"*","resultado":"4.5","unidades":"g/dL","ref":"3.2 - 5.5","abnormal":false},{"estudio":"BILIRRUBINA","flag":"*","resultado":"BILIRRUBINA TOTAL","unidades":"A","ref":"0.2 - 1.0","abnormal":false},{"estudio":"BILIRRUBINA DIRECTA","flag":"A","resultado":"0.7","unidades":"mg/dL","ref":"0.0 - 0.2","abnormal":true},{"estudio":"SODIO","flag":"B","resultado":"124.3","unidades":"mmol/L","ref":"135.0 - 145.0","abnormal":true}],"tableVariant":"standard"}]}]}"###),
    ("\nHEMATOLOGIA\nBIOMETRIA HEMATICA COMPLETA\nEstudio\t\tResultado\tUnidades\tValor de Referencia\nHGB\t\n*\n13.50\ng/dL\t12.20 - 18.10\nTIEMPO DE PROTROMBINA Y TROMBOPLASTINA\nTIEMPO DE PROTROMBINA\t\nA\n14.20\nSEG.\t9.55 - 12.23\n",
     ###"{"departments":[{"key":"HEMATOLOGIA","label":"HEMATOLOGIA","groups":[{"title":"BIOMETRIA HEMATICA COMPLETA","rows":[{"estudio":"HGB","flag":"*","resultado":"13.50","unidades":"g/dL","ref":"12.20 - 18.10","abnormal":false}],"tableVariant":"standard","fluidSource":"","_someNormalized":true},{"title":"TIEMPO DE PROTROMBINA Y TROMBOPLASTINA","rows":[{"estudio":"14.20","flag":"*","resultado":"SEG.\t9.55 - 12.23","unidades":"","ref":"","abnormal":false}],"tableVariant":"standard","fluidSource":"","_someNormalized":true}]}]}"###),
    ("\nEXAMEN GENERAL DE ORINA\nEstudio\t\tResultado\tUnidades\tValor de Referencia\nFISICO\nCOLOR\t\n*\nAMARILLO OSCURO\nQUIMICO\nPH\t\nB\n5.0\n5.5 - 6.5\nPROTEINAS\t\n*\n30\nmg/dL\tNEGATIVO\nSEDIMENTO\nLEUCOCITOS\t\n*\n0-2\n/CAMPO\t0-5/CAMPO\n",
     ###"{"departments":[{"key":"EXAMEN GENERAL DE ORINA","label":"EXAMEN GENERAL DE ORINA","groups":[{"title":"","rows":[{"estudio":"COLOR","flag":"*","resultado":"AMARILLO OSCURO","unidades":"QUIMICO","ref":"","abnormal":false},{"estudio":"PH","flag":"B","resultado":"5.0","unidades":"","ref":"5.5 - 6.5","abnormal":true},{"estudio":"PROTEINAS","flag":"*","resultado":"30","unidades":"mg/dL","ref":"NEGATIVO","abnormal":false},{"estudio":"LEUCOCITOS","flag":"*","resultado":"0-2","unidades":"/CAMPO","ref":"0-5/CAMPO","abnormal":false}],"tableVariant":"standard"}]}]}"###),
    ("\nQUIMICA CLINICA\nEstudio\t\tResultado\tUnidades\tValor de Referencia\nSODIO\nSODIO\t\nCB\n124.3\nmmol/L\t135.0 - 145.0\nPOTASIO\nPOTASIO\t\n*\n4.2\nmmol/L\t3.5 - 5.1\n",
     ###"{"departments":[{"key":"QUIMICA CLINICA","label":"QUIMICA CLINICA","groups":[{"title":"","rows":[{"estudio":"SODIO","flag":"CB","resultado":"124.3","unidades":"mmol/L","ref":"135.0 - 145.0","abnormal":true},{"estudio":"POTASIO","flag":"*","resultado":"4.2","unidades":"mmol/L","ref":"3.5 - 5.1","abnormal":false}],"tableVariant":"standard"}]}]}"###),
    ("\nURIANALISIS\nEXAMEN GENERAL DE ORINA\nEstudio\t\tResultado\tUnidades\tValor de Referencia\nFISICO\nFISICO\n*\n:\nCOLOR\nCOLOR\n*\nAmarillo\nN/A\nASPECTO\nASPECTO\n*\nClaro\nN/A\nQUIMICO\nQUIMICO\n*\n:\nDENSIDAD\nDENSIDAD\n*\n1.008\n1.005 - 1.025\nPH\nPH\n*\n>=9.0\n5.5 - 6.5\nPROTEINAS\nPROTEINAS\nA\n30\nmg/dL\tNEGATIVO\nGLUCOSA\nGLUCOSA\n*\nNegativo\nmg/dL\nNEGATIVO\nCETONAS\nCETONAS\n*\nNegativo\nmg/dL\nNEGATIVO\nBILIRRUBINAS\nBILIRRUBINAS\n*\nNegativo\nNEGATIVO\nSANGRE\nSANGRE\n*\nApr 80\nHem/uL\nNEGATIVO\nNITRITOS\nNITRITOS\n*\nNegativo\nNEGATIVO\nUROBILINOGENO\nUROBILINOGENO\n*\n0.2\nE.U./dL\n0.0 - 1.0\nESTERASA LEUCOCITARIA\nESTERASA LEUCOCITARIA\n*\nApr 70\nLeucocitos/uL\nNEGATIVO\nSEDIMENTO\nSEDIMENTO\n*\n:\nERITROCITOS\nERITROCITOS\n*\n0-5\n/CAMPO\n0-2/CAMPO\nLEUCOCITOS\nLEUCOCITOS\n*\n0-2\n/CAMPO\n0-5/CAMPO\nCELULAS EPITELIALES\nCELULAS EPITELIALES\n*\nAUSENTES\nAUSENTES\nCRISTALES AMORFOS\nCRISTALES AMORFOS\n*\nAUSENTES\nN/A\nBACTERIAS\nBACTERIAS\n*\nESCASAS\nAUSENTES\n",
     ###"{"departments":[{"key":"EXAMEN GENERAL DE ORINA","label":"EXAMEN GENERAL DE ORINA","groups":[{"title":"","rows":[{"estudio":"COLOR","flag":"*","resultado":"Amarillo","unidades":"","ref":"N/A","abnormal":false},{"estudio":"ASPECTO","flag":"*","resultado":"Claro","unidades":"","ref":"N/A","abnormal":false},{"estudio":"DENSIDAD","flag":"*","resultado":"1.008","unidades":"","ref":"1.005 - 1.025","abnormal":false},{"estudio":"PH","flag":"*","resultado":">=9.0","unidades":"","ref":"5.5 - 6.5","abnormal":false},{"estudio":"PROTEINAS","flag":"A","resultado":"30","unidades":"mg/dL","ref":"NEGATIVO","abnormal":true},{"estudio":"GLUCOSA","flag":"*","resultado":"Negativo","unidades":"mg/dL","ref":"NEGATIVO","abnormal":false},{"estudio":"CETONAS","flag":"*","resultado":"Negativo","unidades":"mg/dL","ref":"NEGATIVO","abnormal":false},{"estudio":"BILIRRUBINAS","flag":"*","resultado":"Negativo","unidades":"SANGRE","ref":"NEGATIVO","abnormal":false},{"estudio":"SANGRE","flag":"*","resultado":"Apr 80","unidades":"Hem/uL","ref":"NEGATIVO","abnormal":false},{"estudio":"NITRITOS","flag":"*","resultado":"Negativo","unidades":"UROBILINOGENO","ref":"NEGATIVO","abnormal":false},{"estudio":"UROBILINOGENO","flag":"*","resultado":"0.2","unidades":"E.U./dL","ref":"0.0 - 1.0","abnormal":false},{"estudio":"ESTERASA LEUCOCITARIA","flag":"*","resultado":"Apr 70","unidades":"Leucocitos/uL","ref":"NEGATIVO","abnormal":false},{"estudio":"ERITROCITOS","flag":"*","resultado":"0-5","unidades":"/CAMPO","ref":"0-2/CAMPO","abnormal":false},{"estudio":"LEUCOCITOS","flag":"*","resultado":"0-2","unidades":"/CAMPO","ref":"0-5/CAMPO","abnormal":false},{"estudio":"CELULAS EPITELIALES","flag":"*","resultado":"AUSENTES","unidades":"CRISTALES AMORFOS","ref":"AUSENTES","abnormal":false},{"estudio":"CRISTALES AMORFOS","flag":"*","resultado":"AUSENTES","unidades":"","ref":"N/A","abnormal":false},{"estudio":"BACTERIAS","flag":"*","resultado":"ESCASAS","unidades":"","ref":"AUSENTES","abnormal":false}],"tableVariant":"standard"}]}]}"###),
    ("\nQUIMICA CLINICA\nEstudio\t\tResultado\tUnidades\tValor de Referencia\nCREATININA EN SANGRE\nCREATININA EN SANGRE\t\nA\n1.23\nmg/dL\t0.70 - 1.20\n",
     ###"{"departments":[{"key":"QUIMICA CLINICA","label":"QUIMICA CLINICA","groups":[{"title":"","rows":[{"estudio":"CREATININA EN SANGRE","flag":"A","resultado":"1.23","unidades":"mg/dL","ref":"0.70 - 1.20","abnormal":true}],"tableVariant":"standard"}]}]}"###),
    ("\nQUIMICA CLINICA\nEstudio\t\tResultado\tUnidades\tValor de Referencia\nGLUCOSA\nGLUCOSA\t\n*\n95\nmg/dL\t70 - 100\nCOMENTARIO DE MUESTRA\nOBSERVACION VALOR\t\n*\nTEXTO LIBRE\nOBSERVACIONES\nOBS 1\t\n*\nSIN VALOR CLINICO\nUREA\nUREA\t\n*\n40\nmg/dL\t15 - 45\n",
     ###"{"departments":[{"key":"QUIMICA CLINICA","label":"QUIMICA CLINICA","groups":[{"title":"","rows":[{"estudio":"GLUCOSA","flag":"*","resultado":"95","unidades":"mg/dL","ref":"70 - 100","abnormal":false},{"estudio":"UREA","flag":"*","resultado":"40","unidades":"mg/dL","ref":"15 - 45","abnormal":false}],"tableVariant":"standard"}]}]}"###),
    ("\nQUIMICA CLINICA\nEstudio\t\tResultado\tUnidades\tValor de Referencia\nCOMENTARIO DE LA MUESTRA\nGLUCOSA EN SANGRE\nGLUCOSA EN SANGRE\t\n*\n95\nmg/dL\t70 - 100\nOSMOLARIDAD\nOSMOLARIDAD\t\n*\n277.0\nmmol/L\t275 - 295\nExpediente:\t9000005-1\tSolicitud:\t9000000029\n",
     ###"{"departments":[{"key":"QUIMICA CLINICA","label":"QUIMICA CLINICA","groups":[{"title":"","rows":[{"estudio":"GLUCOSA EN SANGRE","flag":"*","resultado":"95","unidades":"mg/dL","ref":"70 - 100","abnormal":false},{"estudio":"OSMOLARIDAD","flag":"*","resultado":"277.0","unidades":"mmol/L","ref":"275 - 295","abnormal":false}],"tableVariant":"standard"}]}]}"###),
    ("\nQUIMICA CLINICA\nEstudio\t\tResultado\tUnidades\tValor de Referencia\nOSMOLARIDAD\nOSMOLARIDAD\t\n*\n277.0 Expediente:\n9000005-1 Solicitud: 9000000029\n",
     ###"{"departments":[{"key":"QUIMICA CLINICA","label":"QUIMICA CLINICA","groups":[{"title":"","rows":[{"estudio":"OSMOLARIDAD","flag":"*","resultado":"277.0","unidades":"","ref":"","abnormal":false}],"tableVariant":"standard"}]}]}"###),
    ("\nHEMATOLOGIA\nBIOMETRIA HEMATICA COMPLETA\nEstudio\nResultado Unidades\nValor de Referencia\nHGB\n*\n8.16\ng/dL\t13.60 - 17.80\nHCT\nB\n26\n%\t39.5 - 53.1\n",
     ###"{"departments":[{"key":"HEMATOLOGIA","label":"HEMATOLOGIA","groups":[{"title":"BIOMETRIA HEMATICA COMPLETA","rows":[{"estudio":"HGB","flag":"*","resultado":"8.16","unidades":"g/dL","ref":"13.60 - 17.80","abnormal":false},{"estudio":"HCT","flag":"B","resultado":"26","unidades":"%","ref":"39.5 - 53.1","abnormal":true}],"tableVariant":"standard","fluidSource":"","_someNormalized":true}]}]}"###),
    ("\nURIANALISIS\nCUANTIFICACION PROTEINAS EN ORINA 12 O 24 HRS\nEstudio\t\tResultado\tUnidades\tValor de Referencia\nVOLUMEN DE ORINA\t\nA\n100\nml\tN/A\nRESULTADO\t\nA\n0.09\ngr/vol\tNEGATIVO\nOBSERVACIONES\t\n*\n",
     ###"{"departments":[{"key":"URIANALISIS","label":"URIANALISIS","groups":[{"title":"","rows":[{"estudio":"VOLUMEN DE ORINA","flag":"A","resultado":"100","unidades":"ml","ref":"N/A","abnormal":true},{"estudio":"Prot","flag":"A","resultado":"0.09","unidades":"gr/vol","ref":"NEGATIVO","abnormal":true}],"tableVariant":"standard"}]}]}"###),
    ("\nGASOMETRIAS\nEstudio\nResultado Unidades\nValor de Referencia\nLactato\n*\n0.5\nmmol/L\n\n0.4 - 2.0\nHCO3\n*\n26.3\nmmol/L\n22.0 - 30.0\nEX. BASE\n*\n3.6\nmmol/L\n-2.0 - 4.5\nUNIVERSIDAD AUTONOMA DE NUEVO LEON\nREPORTE DE RESULTADOS DE LABORATORIO\n",
     ###"{"departments":[{"key":"GASOMETRIAS","label":"GASOMETRIAS","groups":[{"title":"","rows":[{"estudio":"Lactato","flag":"*","resultado":"0.5","unidades":"mmol/L","ref":"0.4 - 2.0","abnormal":false},{"estudio":"HCO3","flag":"*","resultado":"26.3","unidades":"mmol/L","ref":"22.0 - 30.0","abnormal":false},{"estudio":"EX. BASE","flag":"*","resultado":"3.6","unidades":"mmol/L","ref":"-2.0 - 4.5","abnormal":false}],"tableVariant":"standard","fluidSource":"","_someNormalized":true}]}]}"###),
    ("QUIMICA CLINICA\nEstudio\t\tResultado\tUnidades\tValor de Referencia\nGLUCOSA\t\n*\n94\nmg/dL\t70 - 100\n&\nDr. Ejemplo Sintetico Responsable Sanitario\nel Laboratorio.\nSistema SOME MOP-XX-000\n\"LABORATORIO DEMO\"\nAV. EJEMPLO 100, CENTRO\n2600000000\nPERSONA DEMO SINTETICA",
     ###"{"departments":[{"key":"QUIMICA CLINICA","label":"QUIMICA CLINICA","groups":[{"title":"","rows":[{"estudio":"GLUCOSA","flag":"*","resultado":"94","unidades":"mg/dL","ref":"70 - 100","abnormal":false}],"tableVariant":"standard"}]}]}"###),
    ("",
     ###"{"departments":[]}"###),
    ("hola",
     ###"{"departments":[]}"###),
    ("HEMATOLOGIA\nHEMOGLOBINA\n12.0",
     ###"{"departments":[{"key":"HEMATOLOGIA","label":"HEMATOLOGIA","groups":[{"title":"","rows":[{"estudio":"HEMOGLOBINA","flag":"*","resultado":"12.0","unidades":"","ref":"","abnormal":false}],"tableVariant":"standard","fluidSource":"","_someNormalized":true}]}]}"###),
    ("QUIMICA CLINICA\r\nGLUCOSA\r\nA\r\n250\r\nmg/dL\t70 - 100",
     ###"{"departments":[{"key":"QUIMICA CLINICA","label":"QUIMICA CLINICA","groups":[{"title":"","rows":[{"estudio":"GLUCOSA","flag":"A","resultado":"250","unidades":"mg/dL","ref":"70 - 100","abnormal":true}],"tableVariant":"standard"}]}]}"###),
]

@Suite("Labs SomeTable extra") struct LabsSomeTableExtraTests {
    @Test(arguments: someExtraCases.indices) func someTablesExtra(_ i: Int) throws {
        let c = someExtraCases[i]
        let want = try JSONDecoder().decode(LabJSON.self, from: Data(c.expected.utf8))
        let got: LabJSON = try SomeTableParser.parse(c.input).map { try LabJSON.of($0) } ?? .null
        #expect(got == want, "case \(i)")
    }
}
