import Testing
@testable import RPlusCore

// GENERATED from scratchpad probe-base.mjs (Node oracle, labs-*.mjs). Values are Node output.
private func r(_ v: String?) -> String { v ?? "nil" }
private func r(_ v: Double?) -> String { v.map(jsString) ?? "nil" }
private func r(_ v: Int) -> String { String(v) }
private func r(_ v: LabValorRango) -> String { [v.valor, r(v.min), r(v.max)].joined(separator: "|") }
private func r(_ v: [Double]?) -> String { v.map { $0.map(jsString).joined(separator: ",") } ?? "nil" }
private func r(_ v: [Double?]?) -> String { v.map { $0.map(r).joined(separator: ",") } ?? "nil" }
private func r(_ v: [String?]) -> String { v.map(r).joined(separator: ",") }
private func r(_ v: [String]) -> String { v.joined(separator: "\n") }
private func r(_ v: [String: [Double]]) -> String { v.keys.sorted().map { $0 + "=" + r(v[$0]) }.joined(separator: ";") }
private func r(_ v: [String: Double]) -> String { v.keys.sorted().map { $0 + "=" + jsString(v[$0]!) }.joined(separator: ";") }
private func r(_ v: [String: String]) -> String { v.keys.sorted().map { $0 + "=" + v[$0]! }.joined(separator: ";") }
private let qsText = "QUIMICA CLINICA\nGLUCOSA\t105\tmg/dL\t70 - 100\nCREATININA\t0.9\tmg/dL\t0.5 - 1.3\nDEPURACION DE CREATININA 80 ml/min\nSODIO EN ORINA 45 mmol/L\nSODIO\t*\tmmol/L\t136 - 145\nSODIO\t140\tmmol/L\t136 - 145\nCLORO\t103\t96 - 106\nCOLESTEROL HDL 45 40 - 60\nCOLESTEROL 180 0 - 200\nHEMOGLOBINA GLICOSILADA 6.1 %\nHEMOGLOBINA 13.2 g/dL 12 - 17.5\nALBUMINA 3,2 g/dL 3,5 - 5,2\nPOTASIO EN ORINA 30\nCLORO EN ORINA 60\nINDICE ATEROGENICO 4.1 3.5 RIESGO PROM.\nHCT 41 %\n"
private let coagText = "TIEMPO DE PROTROMBINA Y TROMBOPLASTINA\nTIEMPO DE PROTROMBINA\t\tseg\t10.25 - 13.5\nINR 1.1 0.8 - 1.2\nTIEMPO DE TROMBOPLASTINA 31.2 seg 25 - 35\nFIBRINOGENO EN UNIDADES EQUIVALENTES DE FIBRINOGENO 9000\nFIBRINOGENO 350 mg/dL 200 - 400\nDIMERO D 480 Campo 12345 0 - 500\nTESTIGO 12.1"

@Suite("Labs Base helpers") struct LabsBaseHelpersTests {
    @Test func nodeParity() {
        #expect(r(LabExtract.matchValorLab("abc 12.5 mg").map { "\($0.index):\($0.valor)" }) == "4:12.5")
        #expect(r(LabExtract.matchValorLab("x 1,234.5 y").map { "\($0.index):\($0.valor)" }) == "2:1234.5")
        #expect(r(LabExtract.matchValorLab("v 1e5").map { "\($0.index):\($0.valor)" }) == "nil")
        #expect(r(LabExtract.matchValorLab("Na <0.01 mmol").map { "\($0.index):\($0.valor)" }) == "4:<0.01")
        #expect(r(LabExtract.matchValorLab("K > 1000").map { "\($0.index):\($0.valor)" }) == "4:>1000")
        #expect(r(LabExtract.matchValorLab("none").map { "\($0.index):\($0.valor)" }) == "nil")
        #expect(r(LabExtract.matchValorLab("-3.2 ").map { "\($0.index):\($0.valor)" }) == "0:-3.2")
        #expect(r(LabExtract.matchValorLab("12,5 g").map { "\($0.index):\($0.valor)" }) == "0:12,5")
        #expect(r(LabExtract.matchValorLab("T 0,5-1").map { "\($0.index):\($0.valor)" }) == "2:0,5")
        #expect(r(LabExtract.labValueNumber("12.3")) == "12.3")
        #expect(r(LabExtract.toNum("12.3")) == "12.3")
        #expect(r(LabExtract.fmt("12.3")) == "12.3")
        #expect(r(LabExtract.marcarSegunRango("12.3", 1, 10)) == "12.3*")
        #expect(r(LabExtract.labValueNumber("<0.01*")) == "0.01")
        #expect(r(LabExtract.toNum("<0.01*")) == "nil")
        #expect(r(LabExtract.fmt("<0.01*")) == "<0.01*")
        #expect(r(LabExtract.marcarSegunRango("<0.01*", 1, 10)) == "<0.01**")
        #expect(r(LabExtract.labValueNumber(">1000")) == "1000")
        #expect(r(LabExtract.toNum(">1000")) == "nil")
        #expect(r(LabExtract.fmt(">1000")) == ">1000")
        #expect(r(LabExtract.marcarSegunRango(">1000", 1, 10)) == ">1000*")
        #expect(r(LabExtract.labValueNumber("7,5")) == "7.5")
        #expect(r(LabExtract.toNum("7,5")) == "7.5")
        #expect(r(LabExtract.fmt("7,5")) == "7.5")
        #expect(r(LabExtract.marcarSegunRango("7,5", 1, 10)) == "7,5")
        #expect(r(LabExtract.labValueNumber("abc")) == "nil")
        #expect(r(LabExtract.toNum("abc")) == "nil")
        #expect(r(LabExtract.fmt("abc")) == "abc")
        #expect(r(LabExtract.marcarSegunRango("abc", 1, 10)) == "abc")
        #expect(r(LabExtract.labValueNumber("---")) == "nil")
        #expect(r(LabExtract.toNum("---")) == "nil")
        #expect(r(LabExtract.fmt("---")) == "---")
        #expect(r(LabExtract.marcarSegunRango("---", 1, 10)) == "---")
        #expect(r(LabExtract.labValueNumber("-0")) == "0")
        #expect(r(LabExtract.toNum("-0")) == "0")
        #expect(r(LabExtract.fmt("-0")) == "0")
        #expect(r(LabExtract.marcarSegunRango("-0", 1, 10)) == "-0*")
        #expect(r(LabExtract.labValueNumber("3.10*")) == "3.1")
        #expect(r(LabExtract.toNum("3.10*")) == "3.1")
        #expect(r(LabExtract.fmt("3.10*")) == "3.1*")
        #expect(r(LabExtract.marcarSegunRango("3.10*", 1, 10)) == "3.10*")
        #expect(r(LabExtract.marcarSegunRango("12", nil, 10)) == "12")
        #expect(r(LabExtract.extraer(["GLUCOSA"], "GLUCOSA 105 mg/dL\nUREA: 40\nCREAT -- 1.2\nPH 7.31")) == "105")
        #expect(r(LabExtract.extraer(["NOPE","UREA"], "GLUCOSA 105 mg/dL\nUREA: 40\nCREAT -- 1.2\nPH 7.31")) == "40")
        #expect(r(LabExtract.extraer(["CREAT"], "GLUCOSA 105 mg/dL\nUREA: 40\nCREAT -- 1.2\nPH 7.31")) == "---")
        #expect(r(LabExtract.extraer(["ph"], "GLUCOSA 105 mg/dL\nUREA: 40\nCREAT -- 1.2\nPH 7.31")) == "7.31")
        #expect(r(LabExtract.extraer(["NADA"], "GLUCOSA 105 mg/dL\nUREA: 40\nCREAT -- 1.2\nPH 7.31")) == "---")
        #expect(r(LabExtract.extraer(["X"], "")) == "---")
        #expect(r(LabExtract.extraerConRango(["GLUCOSA"], qsText)) == "105|70|100")
        #expect(r(LabExtract.extraerConRangoSuero(["GLUCOSA"], qsText)) == "105|70|100")
        #expect(r(LabExtract.extraerConRangoPanel(["GLUCOSA"], qsText)) == "105|70|100")
        #expect(r(LabExtract.extraerConRango(["SODIO"], qsText)) == "45|136|145")
        #expect(r(LabExtract.extraerConRangoSuero(["SODIO"], qsText)) == "140|136|145")
        #expect(r(LabExtract.extraerConRangoPanel(["SODIO"], qsText)) == "45|136|145")
        #expect(r(LabExtract.extraerConRango(["CLORO"], qsText)) == "103|96|106")
        #expect(r(LabExtract.extraerConRangoSuero(["CLORO"], qsText)) == "103|96|106")
        #expect(r(LabExtract.extraerConRangoPanel(["CLORO"], qsText)) == "103|96|106")
        #expect(r(LabExtract.extraerConRango(["COLESTEROL"], qsText)) == "45|40|60")
        #expect(r(LabExtract.extraerConRangoSuero(["COLESTEROL"], qsText)) == "180|0|200")
        #expect(r(LabExtract.extraerConRangoPanel(["COLESTEROL"], qsText)) == "45|40|60")
        #expect(r(LabExtract.extraerConRango(["CREATININA"], qsText)) == "0.9|0.5|1.3")
        #expect(r(LabExtract.extraerConRangoSuero(["CREATININA"], qsText)) == "0.9|0.5|1.3")
        #expect(r(LabExtract.extraerConRangoPanel(["CREATININA"], qsText)) == "0.9|0.5|1.3")
        #expect(r(LabExtract.extraerConRango(["HEMOGLOBINA"], qsText)) == "6.1|12|17.5")
        #expect(r(LabExtract.extraerConRangoSuero(["HEMOGLOBINA"], qsText)) == "13.2|12|17.5")
        #expect(r(LabExtract.extraerConRangoPanel(["HEMOGLOBINA"], qsText)) == "6.1|12|17.5")
        #expect(r(LabExtract.extraerConRango(["ALBUMINA"], qsText)) == "3,2|3.5|5.2")
        #expect(r(LabExtract.extraerConRangoSuero(["ALBUMINA"], qsText)) == "3,2|3.5|5.2")
        #expect(r(LabExtract.extraerConRangoPanel(["ALBUMINA"], qsText)) == "3,2|3.5|5.2")
        #expect(r(LabExtract.extraerConRango(["HCT "], qsText)) == "41|nil|nil")
        #expect(r(LabExtract.extraerConRangoSuero(["HCT "], qsText)) == "41|nil|nil")
        #expect(r(LabExtract.extraerConRangoPanel(["HCT "], qsText)) == "41|nil|nil")
        #expect(r(LabExtract.extraerConRango(["NADA"], qsText)) == "---|nil|nil")
        #expect(r(LabExtract.extraerConRangoSuero(["NADA"], qsText)) == "---|nil|nil")
        #expect(r(LabExtract.extraerConRangoPanel(["NADA"], qsText)) == "---|nil|nil")
        #expect(r(LabExtract.extraerIndiceAterogenico(qsText)) == "4.1|0|3.5")
        #expect(r(LabExtract.extraerIndiceAterogenico("INDICE ATEROGENICO 4.1 3.0 - 5.0")) == "4.1|3|5")
        #expect(r(LabExtract.extraerConRangoBH(["LEUCOCITOS"], "BIOMETRIA HEMATICA\nLEUCOCITOS 8.2 4 - 11\nERITROCITOS 4.6 4.2 - 5.4\nEXAMEN GENERAL DE ORINA\nLEUCOCITOS 2-5 /CAMPO\nERITROCITOS 0-2 /CAMPO\n")) == "---|nil|nil")
        #expect(r(LabExtract.extraerConRangoBH(["ERITROCITOS"], "BIOMETRIA HEMATICA\nLEUCOCITOS 8.2 4 - 11\nERITROCITOS 4.6 4.2 - 5.4\nEXAMEN GENERAL DE ORINA\nLEUCOCITOS 2-5 /CAMPO\nERITROCITOS 0-2 /CAMPO\n")) == "---|nil|nil")
        #expect(r(LabExtract.extraerConRangoBH(["LEUCOCITOS"], "EXAMEN GENERAL DE ORINA\nLEUCOCITOS 3 Leucocitos/uL\nBIOMETRIA HEMATICA\nLEUCOCITOS 9.1 4 - 11\n")) == "9.1|4|11")
        #expect(r(LabExtract.extraerConRangoCoag(["TIEMPO DE PROTROMBINA"], coagText)) == "---|nil|nil")
        #expect(r(LabExtract.extraerConRangoCoag(["INR"], coagText)) == "1.1|0.8|1.2")
        #expect(r(LabExtract.extraerConRangoCoag(["TIEMPO DE TROMBOPLASTINA"], coagText)) == "31.2|25|35")
        #expect(r(LabExtract.extraerConRangoCoag(["FIBRINOGENO"], coagText)) == "350|200|400")
        #expect(r(LabExtract.extraerConRangoCoag(["DIMERO D"], coagText)) == "480|0|500")
        #expect(r(LabExtract.extraerConRangoCoag(["INR"], "INR 9.5 0.8 - 1.2")) == "---|nil|nil")
        #expect(r(LabExtract.extraerConRangoCoag(["INR"], "INR 9.5 0.8 - 1.2", maxInr: 12)) == "9.5|0.8|1.2")
        #expect(r(LabExtract.extraerConRangoPanel(["T4 LIBRE"], "T4 LIBRE T4 LIBRE 1.2 ng/dL 0.8 - 1.8")) == "1.2|0.8|1.8")
        #expect(r(LabExtract.fmtLabRanged(LabValorRango(valor: "11", min: nil, max: nil), "Hb", ["Hb": [13, 16], "Cr": [5, 1]])) == "11*")
        #expect(r(LabRefs.resolveLabFieldRange(LabValorRango(valor: "11", min: nil, max: nil), "Hb", ["Hb": [13, 16], "Cr": [5, 1]]).map { [$0.min, $0.max] }) == "13,16")
        #expect(r(LabExtract.fmtLabRanged(LabValorRango(valor: "11", min: 10, max: 12), "Hb", ["Hb": [13, 16], "Cr": [5, 1]])) == "11")
        #expect(r(LabRefs.resolveLabFieldRange(LabValorRango(valor: "11", min: 10, max: 12), "Hb", ["Hb": [13, 16], "Cr": [5, 1]]).map { [$0.min, $0.max] }) == "10,12")
        #expect(r(LabExtract.fmtLabRanged(LabValorRango(valor: "1.5", min: nil, max: nil), "Cr", ["Hb": [13, 16], "Cr": [5, 1]])) == "1.5*")
        #expect(r(LabRefs.resolveLabFieldRange(LabValorRango(valor: "1.5", min: nil, max: nil), "Cr", ["Hb": [13, 16], "Cr": [5, 1]]).map { [$0.min, $0.max] }) == "0.5,1.3")
        #expect(r(LabExtract.fmtLabRanged(LabValorRango(valor: "5", min: nil, max: nil), "Zzz", ["Hb": [13, 16], "Cr": [5, 1]])) == "5")
        #expect(r(LabRefs.resolveLabFieldRange(LabValorRango(valor: "5", min: nil, max: nil), "Zzz", ["Hb": [13, 16], "Cr": [5, 1]]).map { [$0.min, $0.max] }) == "nil")
        #expect(r(LabExtract.fmtLabRanged(LabValorRango(valor: "---", min: nil, max: nil), "Hb", ["Hb": [13, 16], "Cr": [5, 1]])) == "---")
        #expect(r(LabRefs.resolveLabFieldRange(LabValorRango(valor: "---", min: nil, max: nil), "Hb", ["Hb": [13, 16], "Cr": [5, 1]]).map { [$0.min, $0.max] }) == "13,16")
        #expect(r(LabExtract.fmtLabRanged(LabValorRango(valor: "12", min: nil, max: 5), "Hb", ["Hb": [13, 16], "Cr": [5, 1]])) == "12")
        #expect(r(LabRefs.resolveLabFieldRange(LabValorRango(valor: "12", min: nil, max: 5), "Hb", ["Hb": [13, 16], "Cr": [5, 1]]).map { [$0.min, $0.max] }) == "nil,5")
        #expect(r(LabExtract.fmtLabRanged(LabValorRango(valor: "7.50"), "pH", nil, LabRefs.DEFAULT_GASO_REFS)) == "7.5*")
        #expect(r(LabRefs.collectPriorRefsFromHistory([["QS": ["Glu": [70, 100], "Cr": [1, 0]]], nil, ["QS": ["Glu": [60, 110]], "GASES": ["pH": [7.3, 7.5]]]]).mapValues { r($0) }) == "GASES=pH=7.3,7.5;QS=Glu=60,110")
        #expect(r(LabRefs.collectPriorGasRefsFromHistory([["QS": ["Glu": [70, 100], "Cr": [1, 0]]], nil, ["QS": ["Glu": [60, 110]], "GASES": ["pH": [7.3, 7.5]]]])) == "pH=7.3,7.5")
        #expect(r(LabRefs.mergeRefsMap(["Na": [130, 140], "K": [3, 5]], ["Na": [136, 145], "Cl": [2, 1]])) == "K=3,5;Na=136,145")
        #expect(r(LabRefs.mergeRefsBySection(["QS": ["Glu": [70, 100]]], ["QS": ["Glu": [60, 110], "Cr": [0.5, 1.3]], "ESC": ["Na": [1, 0]]]).mapValues { r($0) }) == "QS=Cr=0.5,1.3;Glu=70,100")
        #expect(r(LabRefs.collectPriorBhValuesFromHistory([.init(fecha: "02/10/2026", bh: ["Hto": 30]), .init(fecha: " 03/10/2026 ", bh: nil), .init(fecha: "03/10/2026", bh: ["Ret": 2.1, "Hto": 33]), .init(fecha: "03/10/2026", bh: ["Hto": 99])], "03/10/2026")) == "Hto=33;Ret=2.1")
        #expect(r(LabAnionGap.computeAnionGapValue("140", "103", "16.2")) == "20.799999999999997")
        #expect(r(LabAnionGap.computeAnionGap("140", "103", "16.2")) == "20.8*")
        #expect(r(LabAnionGap.computeAlbuminCorrectedAnionGap("140", "103", "16.2", "3.2")) == "22.8*")
        #expect(r(LabAnionGap.resolveEffectiveAnionGapValue("140", "103", "16.2", "3.2")) == "22.799999999999997")
        #expect(r(LabAnionGap.computeAnionGapValue("140", "100", "24")) == "16")
        #expect(r(LabAnionGap.computeAnionGap("140", "100", "24")) == "16*")
        #expect(r(LabAnionGap.computeAlbuminCorrectedAnionGap("140", "100", "24", "---")) == "---")
        #expect(r(LabAnionGap.resolveEffectiveAnionGapValue("140", "100", "24", "---")) == "16")
        #expect(r(LabAnionGap.computeAnionGapValue("138,5", "101", "22")) == "15.5")
        #expect(r(LabAnionGap.computeAnionGap("138,5", "101", "22")) == "15.5*")
        #expect(r(LabAnionGap.computeAlbuminCorrectedAnionGap("138,5", "101", "22", "4")) == "15.5*")
        #expect(r(LabAnionGap.resolveEffectiveAnionGapValue("138,5", "101", "22", "4")) == "15.5")
        #expect(r(LabAnionGap.computeAnionGapValue("---", "100", "20")) == "nil")
        #expect(r(LabAnionGap.computeAnionGap("---", "100", "20")) == "---")
        #expect(r(LabAnionGap.computeAlbuminCorrectedAnionGap("---", "100", "20", "3")) == "---")
        #expect(r(LabAnionGap.resolveEffectiveAnionGapValue("---", "100", "20", "3")) == "nil")
        #expect(r(LabAnionGap.computeAnionGapValue("145", "100", "25.05")) == "19.950000000000003")
        #expect(r(LabAnionGap.computeAnionGap("145", "100", "25.05")) == "20*")
        #expect(r(LabAnionGap.computeAlbuminCorrectedAnionGap("145", "100", "25.05", "2.5")) == "23.7*")
        #expect(r(LabAnionGap.resolveEffectiveAnionGapValue("145", "100", "25.05", "2.5")) == "23.700000000000003")
        #expect(r(LabAnionGap.computeAnionGapValue("130", "110", "28")) == "-8")
        #expect(r(LabAnionGap.computeAnionGap("130", "110", "28")) == "-8*")
        #expect(r(LabAnionGap.computeAlbuminCorrectedAnionGap("130", "110", "28", "4.5")) == "-9.2*")
        #expect(r(LabAnionGap.resolveEffectiveAnionGapValue("130", "110", "28", "4.5")) == "-9.25")
        #expect(r(LabAnionGap.computeUrinaryAnionGap("45", "30", "60")) == "15")
        #expect(r(LabAnionGap.computeUrinaryAnionGap("45", "---", "60")) == "---")
        #expect(r({ let u = LabAnionGap.extractUrineElectrolytes(qsText); return [u.na, u.k, u.cl] as [String?] }()) == "45,30,60")
        #expect(r(LabGaso.labSectionKey("QS\tGlu 88")) == "QS")
        #expect(r(LabGaso.lineRichnessScore("QS\tGlu 88")) == "11")
        #expect(r(LabGaso.labSectionKey("LCR: Cel 2")) == "LCR:")
        #expect(r(LabGaso.lineRichnessScore("LCR: Cel 2")) == "11")
        #expect(r(LabGaso.labSectionKey("Interpretación gasometría:\tACIDOSIS")) == "INTERPRETACIÓN GASOMETRÍA:")
        #expect(r(LabGaso.lineRichnessScore("Interpretación gasometría:\tACIDOSIS")) == "35")
        #expect(r(LabGaso.labSectionKey("Hb 12")) == "HB")
        #expect(r(LabGaso.lineRichnessScore("Hb 12")) == "7")
        #expect(r(LabGaso.labSectionKey("  PIE\tNEGATIVO*")) == "PIE")
        #expect(r(LabGaso.lineRichnessScore("  PIE\tNEGATIVO*")) == "13")
        #expect(r(LabGaso.labSectionKey("XÁ y")) == "X")
        #expect(r(LabGaso.lineRichnessScore("XÁ y")) == "4")
        #expect(r(LabGaso.labSectionKey("")) == "")
        #expect(r(LabGaso.lineRichnessScore("")) == "0")
        #expect(r(LabGaso.labSectionKey("GASES\tpH 7.31* pCO2 30* Bica 16.2* AG 20.8*")) == "GASES")
        #expect(r(LabGaso.lineRichnessScore("GASES\tpH 7.31* pCO2 30* Bica 16.2* AG 20.8*")) == "79")
        #expect(r(LabGaso.frotisPartKey("FROTIS", "FROTIS  Plaq normales")) == "FROTIS:Plaq")
        #expect(r(LabGaso.frotisPartKey("QS", "QS x")) == "QS")
        #expect(r(LabGaso.dedupeSingletonSections(["QS\tGlu 88 Cr 0.9","ESC\tNa 140 Cl 103 K 4.1","QS\tGlu 88","GASES\tpH 7.31 pCO2 30","OTRO\tx","  ","FROTIS\tCal normal","FROTIS\tPlaq normales","GASES\tpH 7.31* pCO2 30* pO2 88 Lactato 3.1* Bica 16.2* UAG 15*","PFHS\tAlb 3.2 BT 0.8","Interpretación gasometría:\tX"])) == "QS\tGlu 88 Cr 0.9\nESC\tNa 140 Cl 103 K 4.1\nOTRO\tx\nFROTIS\tCal normal\nFROTIS\tPlaq normales\nGASES\tpH 7.31* pCO2 30* pO2 88 Lactato 3.1* Bica 16.2* UAG 15*\nPFHS\tAlb 3.2 BT 0.8\nInterpretación gasometría:\tX")
        #expect(r(LabGaso.reprocessLabResultLines(["QS\tGlu 88 Cr 0.9","ESC\tNa 140 Cl 103 K 4.1","QS\tGlu 88","GASES\tpH 7.31 pCO2 30","OTRO\tx","  ","FROTIS\tCal normal","FROTIS\tPlaq normales","GASES\tpH 7.31* pCO2 30* pO2 88 Lactato 3.1* Bica 16.2* UAG 15*","PFHS\tAlb 3.2 BT 0.8","Interpretación gasometría:\tX"])) == "QS\tGlu 88 Cr 0.9\nESC\tNa 140 Cl 103 K 4.1\nOTRO\tx\nFROTIS\tCal normal\nFROTIS\tPlaq normales\nPFHS\tAlb 3.2 BT 0.8\nGASES\tpH 7.31* pCO2 30* pO2 88 Lactato 3.1* Bica 16.2* AG 20.8* cAG 22.8* UAG 15 Delta-Delta 1.4")
        #expect(r(LabGaso.reprocessLabResultLines(["GASES\tpH 7.50 pCO2 30 Bica 20"], gasRefs: ["pH": [7.3, 7.6]], fallbackElectrolytes: ("138", "100", nil))) == "GASES\tpH 7.5 pCO2 30* Bica 20* AG 18* Delta-Delta 1.5")
        #expect(r({ let e = LabGaso.extractElectrolytesFromResLabs(["QS\tGlu 88 Cr 0.9","ESC\tNa 140 Cl 103 K 4.1","QS\tGlu 88","GASES\tpH 7.31 pCO2 30","OTRO\tx","  ","FROTIS\tCal normal","FROTIS\tPlaq normales","GASES\tpH 7.31* pCO2 30* pO2 88 Lactato 3.1* Bica 16.2* UAG 15*","PFHS\tAlb 3.2 BT 0.8","Interpretación gasometría:\tX"]); return [e.na, e.cl, e.alb] }()) == "140,103,3.2")
        #expect(r(LabGaso.parsePIE(tNorm: "PRUEBA INMUNOLOGICA DE EMBARAZO ORINA NEGATIVO SUERO POSITIVO")) == "PIE\tPOSITIVO*")
        #expect(r(LabGaso.parsePIE(tNorm: "PRUEBA INMUNOLOGICA DE EMBARAZO ORINA negativo")) == "PIE\tNEGATIVO*")
        #expect(r(LabGaso.parsePIE(tNorm: "PRUEBA INMUNOLOGICA DE EMBARAZO sin dato")) == "")
        #expect(r(LabGaso.parsePIE(tNorm: "prueba de embarazo resultado Positivo")) == "PIE\tPOSITIVO*")
        #expect(r(LabGaso.parsePIE(tNorm: "nada")) == "")
        #expect(r(LabGaso.parseGaso(bloque: "GASOMETRIA ARTERIAL\npH 7.50 7.35 - 7.45\nPCO2 30 35 - 45\nPO2 90\nHCO3 30 22 - 28\nCA++ IONIZADO 1.05 1.12 - 1.32\nHCT 39 %", textoQS: "", gasRefs: ["Hto": [40, 50]])) == "GASES\tpH 7.5* pCO2 30* pO2 90* Bica 30* Hto 39* iCa 1.05*")
        #expect(r(LabGaso.buildGasoInterpretacion("GASOMETRIA ARTERIAL\npH 7.50 7.35 - 7.45\nPCO2 30 35 - 45\nPO2 90\nHCO3 30 22 - 28\nCA++ IONIZADO 1.05 1.12 - 1.32\nHCT 39 %", nil)) == "")
        #expect(r(LabGaso.buildGasoInterpretacionFromValues(7.31, 30, 16.2, 20.8, 1.1)) == "INTERPRETACIÓN GASOMETRÍA:\tACIDOSIS METABÓLICA; ANION GAP ELEVADO")
        #expect(r(LabGaso.buildGasoInterpretacionFromValues(7.5, 30, 30, nil, nil)) == "INTERPRETACIÓN GASOMETRÍA:\tALCALOSIS METABÓLICA; ALCALOSIS RESPIRATORIA CONCOMITANTE (PCO2 BAJO)")
        #expect(r(LabGaso.buildGasoInterpretacionFromValues(7.4, 40, 18, 18, 0.5)) == "INTERPRETACIÓN GASOMETRÍA:\tACIDOSIS METABÓLICA CON COMPENSACIÓN RESPIRATORIA; COMPONENTE HIPERCLORÉMICO CON ANION GAP ELEVADO (DELTA-DELTA BAJO)")
        #expect(r(LabGaso.buildGasoInterpretacionFromValues(7.2, 60, 30, 15, 2.5)) == "INTERPRETACIÓN GASOMETRÍA:\tACIDOSIS RESPIRATORIA; ALCALOSIS METABÓLICA CONCOMITANTE (HCO3 ALTO); ALCALOSIS METABÓLICA AGREGADA O ACIDOSIS RESPIRATORIA CRÓNICA CON ANION GAP ELEVADO (DELTA-DELTA ALTO)")
        #expect(r(LabGaso.buildGasoInterpretacionFromValues(7.4, 50, 30, 20, 1.2)) == "INTERPRETACIÓN GASOMETRÍA:\tALCALOSIS METABÓLICA CON COMPENSACIÓN RESPIRATORIA; ALCALOSIS METABÓLICA CONCOMITANTE (HCO3 ALTO); ANION GAP ELEVADO")
        #expect(r(LabGaso.buildGasoInterpretacionFromValues(nil, 40, 24, nil, nil)) == "INTERPRETACIÓN GASOMETRÍA:\tTRASTORNO ÁCIDO-BASE COMPENSADO")
        #expect(r(LabGaso.buildGasoInterpretacionFromValues(7.48, 30, 18, 14, 3)) == "INTERPRETACIÓN GASOMETRÍA:\tALCALOSIS RESPIRATORIA; ACIDOSIS METABÓLICA CONCOMITANTE (HCO3 BAJO); ALCALOSIS METABÓLICA AGREGADA O ACIDOSIS RESPIRATORIA CRÓNICA CON ANION GAP ELEVADO (DELTA-DELTA ALTO)")
    }
}
