import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const INCLUDE_RE = /<!--\s*@include\s+([^\s]+)\s*-->/g;
const GENERATED_BANNER = '<!-- generated by build-ui; edit index.src.html -->\n';


function concatenateStylesheets(html, publicDir) {
  // Match all <link rel="stylesheet" href="/..." > tags starting at /styles/
  const linkRe = /<link\s+rel="stylesheet"\s+href="(\/styles\/[^"]+)">/g;
  let match;
  const styleLinks = [];
  while ((match = linkRe.exec(html))) {
    styleLinks.push(match[1]);
  }
  
  if (styleLinks.length === 0) return html;
  
  // Concatenate CSS files
  let bundledCss = '';
  for (const href of styleLinks) {
    const hrefClean = href.split('?')[0];
    const filePath = path.join(publicDir, hrefClean.slice(1));
    try {
      const css = fs.readFileSync(filePath, 'utf8');
      bundledCss += `/* --- ${hrefClean.slice(1)} --- */\n${css}\n\n`;
    } catch (e) {
      // file not found, skip
    }
  }
  
  // Write bundle
  const bundlePath = path.join(publicDir, 'styles', 'app.bundle.css');
  fs.mkdirSync(path.dirname(bundlePath), { recursive: true });
  fs.writeFileSync(bundlePath, bundledCss);
  
  // Replace all style links with single bundle link
  let result = html;
  for (const href of styleLinks) {
    result = result.replace(
      `<link rel="stylesheet" href="${href}">`,
      ''
    );
  }
  
  // Insert bundle link after /tokens.css
  result = result.replace(
    '<link rel="stylesheet" href="/tokens.css">',
    '<link rel="stylesheet" href="/tokens.css">\n<link rel="stylesheet" href="/styles/app.bundle.css">'
  );
  
  return result;
}

export function collectDuplicateIds(html) {
  const ids = [];
  const re = /\bid=["']([^"']+)["']/g;
  let m;
  while ((m = re.exec(html))) ids.push(m[1]);
  const seen = new Set();
  const dupes = [];
  for (const id of ids) {
    if (seen.has(id)) dupes.push(id);
    seen.add(id);
  }
  return dupes;
}

export function buildUi(srcPath) {
  const absSrc = path.resolve(srcPath);

  function expand(fileAbs, stack) {
    if (stack.includes(fileAbs)) {
      throw new Error(`include cycle: ${fileAbs}`);
    }
    if (!fs.existsSync(fileAbs)) {
      throw new Error(`include not found: ${path.basename(fileAbs)}`);
    }
    const nextStack = [...stack, fileAbs];
    const baseDir = path.dirname(fileAbs);
    const raw = fs.readFileSync(fileAbs, 'utf8');
    return raw.replace(INCLUDE_RE, (_, inc) => {
      return expand(path.resolve(baseDir, inc), nextStack);
    });
  }

  const content = expand(absSrc, []);
  const publicDir = path.dirname(path.dirname(absSrc));
  const contentWithCss = concatenateStylesheets(content, publicDir);
  const dupes = collectDuplicateIds(contentWithCss);
  if (dupes.length) {
    throw new Error(`duplicate id attributes: ${dupes.join(', ')}`);
  }
  return GENERATED_BANNER + contentWithCss;
}

const isMain = process.argv[1] === fileURLToPath(import.meta.url);
if (isMain) {
  const check = process.argv.includes('--check');
  const publicDir = path.join(process.cwd(), 'public');
  const src = path.join(publicDir, 'index.src.html');
  const dest = path.join(publicDir, 'index.html');
  if (!fs.existsSync(src)) {
    console.error('missing public/index.src.html');
    process.exit(1);
  }
  const built = buildUi(src);
  if (check) {
    const onDisk = fs.existsSync(dest) ? fs.readFileSync(dest, 'utf8') : '';
    if (onDisk !== built) {
      console.error('index.html out of date; run npm run build:ui');
      process.exit(1);
    }
    process.exit(0);
  }
  fs.writeFileSync(dest, built);
  console.log('wrote public/index.html');
}
